# GitHub Actions workflow
name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - master
      - dev

permissions:
  contents: read
  packages: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build and load the image into the local Docker daemon
    - name: Build Docker image
      run: docker buildx build --load -t ghcr.io/${{ github.repository }}/levisdrive:latest .

    # Run a simple test
    - name: Run simple test
      run: docker run --rm ghcr.io/${{ github.repository }}/levisdrive:latest

    # Push the image to GHCR (only if the test passes)
    - name: Push Docker image to GitHub Container Registry
      run: docker push ghcr.io/${{ github.repository }}/levisdrive:latest
